### ISSUE TITLE
Clean up Foundation theme

### ISSUE THREAD

**Issue by pdt256** [inklabs/kommerce-core#108]
The Foundation theme should:
* be a minimalistic html/scss base theme
* be easy to extend and customize
* pass all acceptance tests
* closely resemble these screenshots/wireframes: https://inklabs.github.io/kommerce-laravel/

**Comment by jasonraimondi** [comment]
Have a decent base up so far, check out https://inklabs.github.io/kommerce-laravel/foundation-theme.html for a preview, or here is a sneak peek. 

![kt-foundation-product-detail](https://cloud.githubusercontent.com/assets/5787967/22581227/60063ee6-e993-11e6-8c54-f142592f1c36.png)
![kt-foundation-cart](https://cloud.githubusercontent.com/assets/5787967/22581228/6017f2bc-e993-11e6-8e8d-592d564c7beb.png)
![kt-foundation-home](https://cloud.githubusercontent.com/assets/5787967/22581230/60211694-e993-11e6-992a-e910fcd483f0.png)
![kt-foundation-cart-order-summary](https://cloud.githubusercontent.com/assets/5787967/22581229/601f6254-e993-11e6-9a02-4621ff818a77.png)
![kt-foundation-cart-item-added](https://cloud.githubusercontent.com/assets/5787967/22581231/60249990-e993-11e6-9f60-ac5b42ffa6d5.png)

**Comment by jasonraimondi** [comment]
Just a small status update. I've been working on cleaning up the Foundation store theme. Overall, it is coming along pretty well. We ended up needing to use a node.js/webpack build for the front end assets because there was an issue with leafo/scss and foundation the way it uses mixins: https://github.com/leafo/scssphp/issues/446

I've been working on several of the mobile views, as well as adding a shopping cart preview to the productShow screen similar to Amazon, right now it is just json on the sidebar:

![screen shot 2017-02-06 at 9 25 30 pm](https://cloud.githubusercontent.com/assets/5787967/22678949/36f72402-ecb3-11e6-81ab-38b652d1f467.png)
![screen shot 2017-02-06 at 9 25 28 pm](https://cloud.githubusercontent.com/assets/5787967/22678950/36f81a2e-ecb3-11e6-8235-21928c7cd24a.png)

The goal is to finish foundation as soon as possible as a base theme with minimal javascript, and then extend it with the cardinal theme.

**Comment by jasonraimondi** [comment]
![screen shot 2017-02-08 at 7 00 37 pm](https://cloud.githubusercontent.com/assets/5787967/22767564/f0ad920e-ee30-11e6-884a-cf90b02ed7ce.png)
![screen shot 2017-02-08 at 7 00 34 pm](https://cloud.githubusercontent.com/assets/5787967/22767565/f0c06ee2-ee30-11e6-906d-054b0f9b6306.png)

Previews of the Added to Cart screens in both desktop + mobile view, the mobile view needs some gutters still but thats coming after I eat some dinner 👍

**Comment by jasonraimondi** [comment]
![screen shot 2017-02-08 at 10 16 13 pm](https://cloud.githubusercontent.com/assets/5787967/22771838/3d290f6a-ee4e-11e6-8226-ed9ab5f9dad7.png)
